import banach_algebra_techniques_applied_functions_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace banach_algebra_techniques_applied_functions_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end banach_algebra_techniques_applied_functions_theorem_canonical_lane_mathlib
end HautevilleHouse
